### PR TITLE
Frontend/master

### PR DESCRIPTION
**Pull request by krampus-nuggets**
1. Removed Unnecessary Junk
2. Setup direct link to GraphQL API

### CODE REVIEW

**Comment by AmoDinho** [comment]
@krampus-nuggets Cool everything works. Just have to fix the change I requested above

**Comment by krampus-nuggets** [comment]
> In `index.js` why are you removing the stages?

@AmoDinho I'd prefer purging to bare-bones and working up from there.

**Comment by AmoDinho** [comment]
Yeah that makes no sense. What happens when you are working locally and then also need to test the production API?

**Comment by AmoDinho** [comment]
Is there something you do not understand about the stages?

**Comment by AmoDinho** [comment]
@krampus-nuggets ?

**Pull request merged**
